"""Repository rule that generates a BUILD file with all devtools targets.

This is used by the module extension to create a repo (e.g. @dev) where
consumers can `bazel run @dev//:clang_format` without adding anything to their BUILD files.
"""

def _devtools_repo_impl(rctx):
    """Generate a BUILD.bazel with all devtools targets."""

    lines = [
        '"""Auto-generated by rules_devtools module extension. DO NOT EDIT."""',
        "",
        'load("@rules_devtools//bazel:bep_report.bzl", "bep_report")',
        'load("@rules_devtools//bazel:buildifier.bzl", "buildifier")',
        'load("@rules_devtools//bazel:buildozer.bzl", "buildozer")',
        'load("@rules_devtools//bazel:depgraph.bzl", "depgraph")',
        'load("@rules_devtools//cc:clang_format.bzl", "clang_format")',
        'load("@rules_devtools//cc:clang_tidy.bzl", "clang_tidy")',
        'load("@rules_devtools//cc:compile_commands.bzl", "compile_commands")',
        'load("@rules_devtools//cc:ctags.bzl", "ctags")',
        'load("@rules_devtools//cc:iwyu.bzl", "iwyu")',
        'load("@rules_devtools//cc:sast.bzl", "sast")',
        'load("@rules_devtools//cc:unused_deps.bzl", "unused_deps")',
        'load("@rules_devtools//format_all:format_all.bzl", "format_all")',
        'load("@rules_devtools//lint_all:lint_all.bzl", "lint_all")',
        'load("@rules_devtools//py:ruff.bzl", "ruff")',
        'load("@rules_devtools//py:black.bzl", "black")',
        'load("@rules_devtools//py:mypy.bzl", "mypy")',
        "",
    ]

    # 1. compile_commands
    cc_kwargs = {"name": repr("compile_commands")}
    if rctx.attr.targets:
        cc_kwargs["targets"] = repr(rctx.attr.targets)
    if rctx.attr.exclude_headers:
        cc_kwargs["exclude_headers"] = repr(rctx.attr.exclude_headers)
    if rctx.attr.exclude_external_sources:
        cc_kwargs["exclude_external_sources"] = "True"
    lines.append(_render_call("compile_commands", cc_kwargs))

    # 2. clang_format
    fmt_kwargs = {"name": repr("clang_format")}
    if rctx.attr.format_srcs:
        fmt_kwargs["srcs"] = repr(rctx.attr.format_srcs)
    if rctx.attr.clang_format_hermetic:
        fmt_kwargs["hermetic"] = repr(rctx.attr.clang_format_hermetic)
    fmt_kwargs["system"] = repr(rctx.attr.clang_format_system)
    lines.append(_render_call("clang_format", fmt_kwargs))

    # 3. clang_tidy
    lint_kwargs = {"name": repr("clang_tidy")}
    lint_srcs = rctx.attr.lint_srcs or rctx.attr.format_srcs
    if lint_srcs:
        lint_kwargs["srcs"] = repr(lint_srcs)
    if rctx.attr.clang_tidy_hermetic:
        lint_kwargs["hermetic"] = repr(rctx.attr.clang_tidy_hermetic)
    lint_kwargs["system"] = repr(rctx.attr.clang_tidy_system)
    lines.append(_render_call("clang_tidy", lint_kwargs))

    # 4. sast
    sast_kwargs = {"name": repr("sast")}
    sast_srcs = rctx.attr.sast_srcs or rctx.attr.format_srcs
    if sast_srcs:
        sast_kwargs["srcs"] = repr(sast_srcs)
    if rctx.attr.analyzers:
        sast_kwargs["analyzers"] = repr(rctx.attr.analyzers)
    lines.append(_render_call("sast", sast_kwargs))

    # 5. iwyu
    iwyu_kwargs = {"name": repr("iwyu")}
    if rctx.attr.iwyu_hermetic:
        iwyu_kwargs["hermetic"] = repr(rctx.attr.iwyu_hermetic)
    iwyu_kwargs["system"] = repr(rctx.attr.iwyu_system)
    lines.append(_render_call("iwyu", iwyu_kwargs))

    # 6. unused_deps
    ud_kwargs = {"name": repr("unused_deps")}
    if rctx.attr.targets:
        ud_kwargs["targets"] = repr(rctx.attr.targets)
    lines.append(_render_call("unused_deps", ud_kwargs))

    # 7. bep_report
    lines.append(_render_call("bep_report", {"name": repr("bep_report")}))

    # 8. depgraph
    lines.append(_render_call("depgraph", {"name": repr("depgraph")}))

    # 9. ctags
    ctags_kwargs = {"name": repr("ctags")}
    ctags_srcs = rctx.attr.ctags_srcs or rctx.attr.format_srcs
    if ctags_srcs:
        ctags_kwargs["srcs"] = repr(ctags_srcs)
    if rctx.attr.ctags_hermetic:
        ctags_kwargs["hermetic"] = repr(rctx.attr.ctags_hermetic)
    ctags_kwargs["system"] = repr(rctx.attr.ctags_system)
    if rctx.attr.enable_cscope:
        ctags_kwargs["cscope"] = "True"
    lines.append(_render_call("ctags", ctags_kwargs))

    # 10. buildifier
    bf_kwargs = {"name": repr("buildifier")}
    if rctx.attr.buildifier_srcs:
        bf_kwargs["srcs"] = repr(rctx.attr.buildifier_srcs)
    bf_kwargs["mode"] = repr(rctx.attr.buildifier_mode)
    bf_kwargs["lint"] = repr(rctx.attr.buildifier_lint)
    if rctx.attr.buildifier_warnings:
        bf_kwargs["warnings"] = repr(rctx.attr.buildifier_warnings)
    if rctx.attr.buildifier_hermetic:
        bf_kwargs["hermetic"] = repr(rctx.attr.buildifier_hermetic)
    bf_kwargs["system"] = repr(rctx.attr.buildifier_system)
    lines.append(_render_call("buildifier", bf_kwargs))

    # 11. buildozer
    bo_kwargs = {"name": repr("buildozer")}
    if rctx.attr.buildozer_hermetic:
        bo_kwargs["hermetic"] = repr(rctx.attr.buildozer_hermetic)
    bo_kwargs["system"] = repr(rctx.attr.buildozer_system)
    lines.append(_render_call("buildozer", bo_kwargs))

    # 12. format_all (smart dispatch: clang-format + buildifier + ruff)
    fa_kwargs = {"name": repr("format_all")}
    if rctx.attr.format_srcs:
        fa_kwargs["cpp_srcs"] = repr(rctx.attr.format_srcs)
    if rctx.attr.buildifier_srcs:
        fa_kwargs["bazel_srcs"] = repr(rctx.attr.buildifier_srcs)
    if rctx.attr.py_srcs:
        fa_kwargs["py_srcs"] = repr(rctx.attr.py_srcs)
    if rctx.attr.clang_format_hermetic:
        fa_kwargs["clang_format_hermetic"] = repr(rctx.attr.clang_format_hermetic)
    fa_kwargs["clang_format_system"] = repr(rctx.attr.clang_format_system)
    if rctx.attr.buildifier_hermetic:
        fa_kwargs["buildifier_hermetic"] = repr(rctx.attr.buildifier_hermetic)
    fa_kwargs["buildifier_system"] = repr(rctx.attr.buildifier_system)
    fa_kwargs["ruff_system"] = repr(rctx.attr.ruff_system)
    lines.append(_render_call("format_all", fa_kwargs))

    # 13. lint_all (smart dispatch: clang-tidy + buildifier-lint + ruff)
    la_kwargs = {"name": repr("lint_all")}
    la_cpp_srcs = rctx.attr.lint_srcs or rctx.attr.format_srcs
    if la_cpp_srcs:
        la_kwargs["cpp_srcs"] = repr(la_cpp_srcs)
    if rctx.attr.buildifier_srcs:
        la_kwargs["bazel_srcs"] = repr(rctx.attr.buildifier_srcs)
    if rctx.attr.py_srcs:
        la_kwargs["py_srcs"] = repr(rctx.attr.py_srcs)
    if rctx.attr.clang_tidy_hermetic:
        la_kwargs["clang_tidy_hermetic"] = repr(rctx.attr.clang_tidy_hermetic)
    la_kwargs["clang_tidy_system"] = repr(rctx.attr.clang_tidy_system)
    if rctx.attr.buildifier_hermetic:
        la_kwargs["buildifier_hermetic"] = repr(rctx.attr.buildifier_hermetic)
    la_kwargs["buildifier_system"] = repr(rctx.attr.buildifier_system)
    la_kwargs["ruff_system"] = repr(rctx.attr.ruff_system)
    lines.append(_render_call("lint_all", la_kwargs))

    # 14. ruff
    ruff_kwargs = {"name": repr("ruff")}
    if rctx.attr.py_srcs:
        ruff_kwargs["srcs"] = repr(rctx.attr.py_srcs)
    ruff_kwargs["system"] = repr(rctx.attr.ruff_system)
    lines.append(_render_call("ruff", ruff_kwargs))

    # 15. black
    black_kwargs = {"name": repr("black")}
    if rctx.attr.py_srcs:
        black_kwargs["srcs"] = repr(rctx.attr.py_srcs)
    black_kwargs["system"] = repr(rctx.attr.black_system)
    lines.append(_render_call("black", black_kwargs))

    # 16. mypy
    mypy_kwargs = {"name": repr("mypy")}
    if rctx.attr.py_srcs:
        mypy_kwargs["srcs"] = repr(rctx.attr.py_srcs)
    mypy_kwargs["system"] = repr(rctx.attr.mypy_system)
    lines.append(_render_call("mypy", mypy_kwargs))

    rctx.file("BUILD.bazel", content = "\n".join(lines) + "\n")

def _render_call(fn_name, kwargs):
    """Render a Starlark function call as a string."""
    parts = []
    for k, v in kwargs.items():
        parts.append("    {} = {},".format(k, v))
    return "{}(\n{}\n)\n".format(fn_name, "\n".join(parts))

devtools_repo = repository_rule(
    implementation = _devtools_repo_impl,
    attrs = {
        "targets": attr.string(default = "//...", doc = "Bazel targets to analyze."),
        "format_srcs": attr.string_list(doc = "Glob patterns for clang_format/clang_tidy/sast/ctags sources."),
        "lint_srcs": attr.string_list(doc = "Glob patterns for clang_tidy. Defaults to format_srcs."),
        "sast_srcs": attr.string_list(doc = "Glob patterns for sast. Defaults to format_srcs."),
        "ctags_srcs": attr.string_list(doc = "Glob patterns for ctags. Defaults to format_srcs."),
        "buildifier_srcs": attr.string_list(doc = "Glob patterns for buildifier sources."),
        "clang_format_system": attr.string(default = "clang-format"),
        "clang_format_hermetic": attr.string(doc = "Label string to hermetic clang-format binary."),
        "clang_tidy_system": attr.string(default = "clang-tidy"),
        "clang_tidy_hermetic": attr.string(doc = "Label string to hermetic clang-tidy binary."),
        "iwyu_system": attr.string(default = "include-what-you-use"),
        "iwyu_hermetic": attr.string(doc = "Label string to hermetic IWYU binary."),
        "ctags_system": attr.string(default = "ctags"),
        "ctags_hermetic": attr.string(doc = "Label string to hermetic ctags binary."),
        "buildifier_system": attr.string(default = "buildifier"),
        "buildifier_hermetic": attr.string(doc = "Label string to hermetic buildifier binary."),
        "buildozer_system": attr.string(default = "buildozer"),
        "buildozer_hermetic": attr.string(doc = "Label string to hermetic buildozer binary."),
        "analyzers": attr.string_list(doc = "List of analyzers for sast target."),
        "exclude_headers": attr.string(doc = "Header exclusion mode for compile_commands."),
        "exclude_external_sources": attr.bool(default = False),
        "enable_cscope": attr.bool(default = False),
        "buildifier_mode": attr.string(default = "fix"),
        "buildifier_lint": attr.string(default = "warn"),
        "buildifier_warnings": attr.string(default = ""),
        "py_srcs": attr.string_list(doc = "Glob patterns for Python sources."),
        "ruff_system": attr.string(default = "ruff"),
        "black_system": attr.string(default = "black"),
        "mypy_system": attr.string(default = "mypy"),
    },
)
